name: commons
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  beamer: ^1.5.3
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  shared_preferences: ^2.2.1
  permission_handler: ^10.4.3
  package_info_plus: ^8.0.0
  # share_plus: ^11.0.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.3
  # connectivity_plus: ^2.3.8
  flutter_internet_signal: ^0.0.30
  flutter_internet_speed_test: ^1.0.4
  opencv_dart: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
flutter: